name: Update stars feed
on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * *
jobs:
  awesome-stars:
    name: Update stars feed
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: starred --username jdecool --repository stars-feed --sort --token ${GITHUB_TOKEN} --message "$(date '+%Y-%m-%d') Update"
